// Code generated by a script to simplify the import process.
// This file aggregates all the functions from various packages in the library
// into a single package-level file. This allows users to import only this
// package instead of importing multiple sub-packages.
// Authors of source code: Sanya239, Nosorozhek
// This file and comment are generated by ChatGPT

package all

import (
	"github.com/aHaHaTeam/p5js-wasm-go/3d"
	"github.com/aHaHaTeam/p5js-wasm-go/color"
	"github.com/aHaHaTeam/p5js-wasm-go/environment"
	"github.com/aHaHaTeam/p5js-wasm-go/events"
	"github.com/aHaHaTeam/p5js-wasm-go/rendering"
	"github.com/aHaHaTeam/p5js-wasm-go/shape"
	"github.com/aHaHaTeam/p5js-wasm-go/structure"
	"github.com/aHaHaTeam/p5js-wasm-go/typography"
	"github.com/aHaHaTeam/p5js-wasm-go/utils"
)

var Alpha = color.Alpha
var Blue = color.Blue
var Brightness = color.Brightness
var Color = color.Color
var Green = color.Green
var Hue = color.Hue
var LerpColor = color.LerpColor
var Lightness = color.Lightness
var Red = color.Red
var Saturation = color.Saturation
var Background = color.Background
var Clear = color.Clear
var ColorMode = color.ColorMode
var Fill = color.Fill
var NoFill = color.NoFill
var NoStroke = color.NoStroke
var Stroke = color.Stroke
var Erase = color.Erase
var NoErase = color.NoErase

var Describe = environment.Describe
var DescribeElement = environment.DescribeElement
var TextOutput = environment.TextOutput
var GridOutput = environment.GridOutput
var Print = environment.Print
var FrameCount = environment.FrameCount
var DeltaTime = environment.DeltaTime
var Focused = environment.Focused
var Cursor = environment.Cursor
var FrameRate = environment.FrameRate
var GetTargetFrameRate = environment.GetTargetFrameRate
var NoCursor = environment.NoCursor
var WebglVersion = environment.WebglVersion
var DisplayWidth = environment.DisplayWidth
var DisplayHeight = environment.DisplayHeight
var WindowWidth = environment.WindowWidth
var WindowHeight = environment.WindowHeight
var WindowResized = environment.WindowResized
var Width = environment.Width
var Height = environment.Height
var FullScreen = environment.FullScreen
var PixelDensity = environment.PixelDensity
var DisplayDensity = environment.DisplayDensity
var GetURL = environment.GetURL
var GetURLPath = environment.GetURLPath
var GetURLParams = environment.GetURLParams

var CreateCanvas = rendering.CreateCanvas
var ResizeCanvas = rendering.ResizeCanvas
var NoCanvas = rendering.NoCanvas
var CreateGraphics = rendering.CreateGraphics
var CreateFramebuffer = rendering.CreateFramebuffer
var ClearDepth = rendering.ClearDepth
var BlendMode = rendering.BlendMode
var SetAttributes = rendering.SetAttributes

var AnyFuncReturnErr = utils.AnyFuncReturnErr
var AnyFuncReturnJsValue = utils.AnyFuncReturnJsValue
var FuncWithCallbacksReturnJsValue = utils.FuncWithCallbacksReturnJsValue
var GetGlobalValue = utils.GetGlobalValue
var BindJsFunc = utils.BindJsFunc
var AnyFuncReturnInt = utils.AnyFuncReturnInt

var LoadShader = _3d.LoadShader
var CreateShader = _3d.CreateShader
var CreateFilterShader = _3d.CreateFilterShader
var Shader = _3d.Shader
var ResetShader = _3d.ResetShader
var Texture = _3d.Texture
var TextureMode = _3d.TextureMode
var TextureWrap = _3d.TextureWrap
var NormalMaterial = _3d.NormalMaterial
var AmbientMaterial = _3d.AmbientMaterial
var EmissiveMaterial = _3d.EmissiveMaterial
var SpecularMaterial = _3d.SpecularMaterial
var Shininess = _3d.Shininess
var Metalness = _3d.Metalness

var KeyIsPressed = events.KeyIsPressed
var Key = events.Key
var KeyCode = events.KeyCode
var KeyPressed = events.KeyPressed
var KeyReleased = events.KeyReleased
var KeyTyped = events.KeyTyped
var KeyIsDown = events.KeyIsDown
var MovedX = events.MovedX
var MovedY = events.MovedY
var MouseX = events.MouseX
var MouseY = events.MouseY
var PmouseX = events.PmouseX
var PmouseY = events.PmouseY
var WinMouseX = events.WinMouseX
var WinMouseY = events.WinMouseY
var PwinMouseX = events.PwinMouseX
var PwinMouseY = events.PwinMouseY
var MouseButton = events.MouseButton
var MouseIsPressed = events.MouseIsPressed
var MouseMoved = events.MouseMoved
var MouseDragged = events.MouseDragged
var MousePressed = events.MousePressed
var MouseReleased = events.MouseReleased
var MouseClicked = events.MouseClicked
var DoubleClicked = events.DoubleClicked
var MouseWheel = events.MouseWheel
var RequestPointerLock = events.RequestPointerLock
var ExitPointerLock = events.ExitPointerLock

var Arc = shape.Arc
var Ellipse = shape.Ellipse
var Circle = shape.Circle
var Line = shape.Line
var Point = shape.Point
var Quad = shape.Quad
var Rect = shape.Rect
var Square = shape.Square
var Triangle = shape.Triangle
var NoSmooth = shape.NoSmooth
var EllipseMode = shape.EllipseMode
var RectMode = shape.RectMode
var Smooth = shape.Smooth
var StrokeCap = shape.StrokeCap
var StrokeJoin = shape.StrokeJoin
var StrokeWeight = shape.StrokeWeight

var Preload = structure.Preload
var Setup = structure.Setup
var Draw = structure.Draw
var Remove = structure.Remove
var NoLoop = structure.NoLoop
var Loop = structure.Loop
var IsLooping = structure.IsLooping
var Push = structure.Push
var Pop = structure.Pop
var Redraw = structure.Redraw

var TextAlign = typography.TextAlign
var TextLeading = typography.TextLeading
var TextSize = typography.TextSize
var TextStyle = typography.TextStyle
var TextWidth = typography.TextWidth
var TextAscent = typography.TextAscent
var TextDescent = typography.TextDescent
var TextWrap = typography.TextWrap
var LoadFont = typography.LoadFont
var Text = typography.Text
var TextFont = typography.TextFont
